server:
  port: 9000

spring:
  # mail send setting
  mail:
    host: smtp.naver.com
    port: 465
    username: dj9099    # github 유출 금지
    password:         # github 유출 금지
    protocol: smtp
    properties:
        mail:
            smtp:
                auth: true
                ssl.enable: true


  # database setting
  datasource:
    url: jdbc:mariadb://localhost:3306/eventdb
    username: root
    password: mariadb
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # DBMS dialect setting
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      # ddl
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL log
    database: mysql

# log level setting
logging:
  level:
    root: info
    com.study.event: debug
    org.hibernate.SQL: debug



jwt:
  secret-key: L6h/xMxGO53HQmR/OB99qR/y0kTr2CAyaI5RqBIX184=  # 토큰발급시와 토큰위조검사시 사용할 서명
  access-token-validity-time: 3600000  # 1시간 (ms)
  refresh-token-validity-time: 604800000 # 7일 (ms)




